config:
  aws:region: ap-southeast-2
  aws:accessKey: test
  aws:secretKey: test
  aws:skipCredentialsValidation: "true"
  aws:skipMetadataApiCheck: "true"
  aws:skipRequestingAccountId: "true"
  aws:endpoints:
    - sqs: http://localhost:4568
      lambda: http://localhost:4568
      iam: http://localhost:4568
encryptionsalt: v1:e6Sor8Jp11s=:v1:h1BbwexMu/ZLaDyc:WZzj9dG4rXVv1G8EJAJEzuAV5VEdIQ==
