config:
  aws:region: ap-southeast-2
  aws:accessKey: test
  aws:secretKey: test
  aws:skipCredentialsValidation: "true"
  aws:skipMetadataApiCheck: "true"
  aws:skipRequestingAccountId: "true"
  aws:endpoints:
    - sqs: http://localhost:4570
      lambda: http://localhost:4570
      iam: http://localhost:4570
encryptionsalt: v1:+0wNlVKzd6I=:v1:afLFHRrEFjqktPBc:eUmJSeTSkoIP4g6Dl9b6OiRCz8GqLQ==
